### ISSUE TITLE
Code stolen

### ISSUE THREAD

**Issue by amigaharry** [AdamKeher/XCopyStandalone#1]
Most of this code was stolen from https://nickslabor.niteto.de/download/
Thats really sad...

**Comment by AdamKeher** [comment]
The project uses some of the floppy interface code from Nick's open source project. This implementation operates standalone from a PC using a LCD screen and SD card + ESP for a websocket app. 90% of the code, schematic's and PCB's do not draw on Nick's excellent and generous work. Suitable attribution has been given and the license type chosen for the project is compatible with Nick's.
